spring:
  application:
    name: elocate
  datasource:
    url: jdbc:postgresql://ep-gentle-salad-admc88pi-pooler.c-2.us-east-1.aws.neon.tech/elocate?sslmode=require
    username: neondb_owner
    password: npg_veoMfz2N9xds
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: kasumalesh@gmail.com
    password: dwqx mclv bkkf soxt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp

server:
  port: 8080
  servlet:
    context-path: /elocate

app:
  jwt:
    secret: elocate-super-secret-key-change-in-production-minimum-256-bits-required
    expiration-ms: 86400000 # 24 hours
  otp:
    expiry-minutes: 10
    max-attempts: 3

auth0:
  domain: elocate-dev.us.auth0.com
  clientId: gSMm494WIxE59MtZxODuYvdCRy4yFT10
  clientSecret: NalHurNjv35rQu_zgmR_vkOHB2-OmuOofKBY2lMRUz4Lu3d6F2RQVM9T8REVqHtZ
  connection: Username-Password-Authentication

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
